### PR TITLE
uploaded file 

### PR DESCRIPTION
**Pull request by klaraweissbe**

### CODE REVIEW

**Comment by klaraweissbe** [comment]
Wiki project from Klara Weißbender

**Review by felixdidi — CHANGES_REQUESTED** [review]
Hi, please remove the exercise file for the in-class exercise (summary of the text) as I do not want to merge this file into the base repository. Thanks! 😄

**Comment by klaraweissbe** [comment]
I removed the file successfully.

**Comment by klaraweissbe** [comment]
Just one question. Did everything work out well with the wiki exercise or do I need to change anything as well?

**Comment by felixdidi** [comment]
Looks all good now, thanks! 👍

**Pull request merged**
